name: Generate vector basemap PMTiles
description: Generate vector basemap PMTiles

inputs:
  artifact-retention-days:
    description: Optional input set PMTiles artifact retention days
    required: false
  cache-data-sources:
    description: Optional input to set if data sources should be cached
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Prepare Java environment
      uses: ./.github/actions/prepare-java-environment

    - name: Cache vector basemap data sources
      uses: actions/cache@v4
      if: ${{ inputs.cache-data-sources == 'true' }}
      with:
        path: vector/data/sources
        key: vector-basemap-data-sources

    - name: Generate vector basemap PMTiles
      shell: bash
      run: ./gradlew -q run | tee logs-planetiler-basemap-vector.txt

    - name: Upload PMTiles artifact
      uses: actions/upload-artifact@v4
      with:
        name: vector-basemap-pmtiles
        path: vector/data/output
        if-no-files-found: error
        retention-days: ${{ inputs.artifact-retention-days }}
        compression-level: 0

    - name: Upload PlaneTiler generate logs
      uses: actions/upload-artifact@v4
      with:
        name: logs-planetiler-basemap-vector
        path: logs-planetiler-basemap-vector.txt
        if-no-files-found: error

