[versions]
planetiler = "0.7.0"
geotools = "29.2"

[libraries]
planetiler = { module = "com.onthegomap.planetiler:planetiler-core", version.ref = "planetiler" }
geotoolsProcessGeometry = { module = "org.geotools:gt-process-geometry", version.ref = "geotools" }
