name: "Basemap vector: sync data sources"
run-name: "Basemap vector: sync data sources (${{ inputs.source }})"

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Data source'
        required: true
        default: all
        type: choice
        options:
          - all
          - grpk
          - address-registry

permissions: { }

jobs:
  basemap-vector-datasource-address-registry:
    name: Address registry sync and transform
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: ghcr.io/osgeo/gdal:ubuntu-full-3.9.0
    permissions:
      contents: read
    concurrency: basemap-vector-datasource-address-registry
    if: ${{ inputs.source == 'all' || inputs.source == 'address-registry' }}
    environment:
      name: basemap-vector-datasource-address-registry
      url: https://cdn.startupgov.lt/tiles/vector/sources/address-registry/houses-espg-4326.gpkg.zip
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git csvkit coreutils

      # Needed only for GitHub action for uploading to S3
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Convert address information to GPKG
        run: ogr2ogr -f GPKG addresses.gpkg "https://www.registrucentras.lt/aduomenys/?byla=adr_stat_lr.csv" -nln info

      # The complete geojson data with all municipalities is updated only once a year. However,
      # when downloaded per municipality, it is updated every month. To ensure we have the latest data,
      # this step pulls data for each municipality individually.
      - name: Convert each municipality's geojson data to GPKG format
        run: |
          curl -sf "https://www.registrucentras.lt/aduomenys/?byla=adr_savivaldybes.csv" | csvcut -d "|" -c "SAV_KODAS" | tail -n +2 | while read -r code; do
            echo "Converting https://www.registrucentras.lt/aduomenys/?byla=adr_gra_$code.json"
          
            ogr2ogr -append -f GPKG addresses.gpkg "https://www.registrucentras.lt/aduomenys/?byla=adr_gra_$code.json" -nln points
          done

      - name: Create output directory
        run: mkdir output

      - name: Generate houses GPKG in EPSG:4326
        run: ogr2ogr -f GPKG -t_srs EPSG:4326 -xyRes "0.0000001" -sql "SELECT points.fid, points.geom, points.AOB_KODAS, info.sav_kodas, points.gyv_kodas, points.gat_kodas, info.nr, info.pasto_kodas, info.korpuso_nr FROM points INNER JOIN info USING (AOB_KODAS) ORDER BY AOB_KODAS" output/houses-espg-4326.gpkg.zip addresses.gpkg -nln houses

      - name: Generate checksum
        working-directory: output
        run: md5 -r houses-espg-4326.gpkg.zip >> checksums.txt

      - name: Upload to S3
        uses: ./.github/actions/rclone-sync
        with:
          s3-endpoint: ${{ vars.S3_ENDPOINT }}
          s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          source-path: output
          destination-path: /tiles/vector/sources/address-registry

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: address-registry-house-numbers
          path: output
          if-no-files-found: error
          compression-level: 0

  basemap-vector-datasource-grpk:
    name: GRPK sync and transform
    runs-on: ubuntu-latest
    # GeoPortal download is really slow. Downloading less than 3 GB takes more than 3 hours :(
    timeout-minutes: 360
    container: ghcr.io/osgeo/gdal:ubuntu-full-3.8.5
    permissions: { }
    concurrency: basemap-vector-datasource-grpk
    if: ${{ inputs.source == 'all' || inputs.source == 'grpk' }}
    environment:
      name: basemap-vector-datasource-grpk
      url: https://cdn.startupgov.lt/tiles/vector/sources/grpk/grpk-espg-4326.shp.zip
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y git coreutils

      # Needed only for GitHub action for uploading to S3
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Download GRPK from GeoPortal
        run: wget -nv https://www.geoportal.lt/download/opendata/GRPK/GRPK_Open_SHP.zip

      - name: Unzip GRPK data source
        run: unzip GRPK_Open_SHP.zip -x "GRPK_Open_SHP/INFO_/*" && rm GRPK_Open_SHP.zip

      - name: Create output directory
        run: mkdir output

      - name: Transform to EPSG:4326
        run: ogr2ogr -f "ESRI Shapefile" -lco ENCODING=UTF-8 -t_srs EPSG:4326 output/grpk-espg-4326.shp.zip GRPK_Open_SHP

      - name: Generate checksum
        working-directory: output
        run: md5 -r grpk-espg-4326.shp.zip >> checksums.txt

      - name: Upload to S3
        uses: ./.github/actions/rclone-sync
        with:
          s3-endpoint: ${{ vars.S3_ENDPOINT }}
          s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          source-path: output
          destination-path: /tiles/vector/sources/grpk


