name: "Basemap vector: publish"
run-name: "Basemap vector: publish (${{ startsWith(github.ref, 'refs/tags/') && 'stable' || 'preview' }})"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  publish-vector-basemap:
    name: Publish vector basemap
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: startsWith(github.ref, 'refs/tags/')
    concurrency: basemap-vector-publish
    with:
      stable: true
      archive-version: ${{ github.ref_name }}
      style-source-url: https://vector.startupgov.lt/vector
      style-glyphs-url: https://basemap.startupgov.lt/vector/font/{fontstack}/{range}.pbf
      style-sprites-base-url: https://basemap.startupgov.lt/vector/sprite
    secrets:
      cloudflare-api-token: ${{  secrets.CLOUDFLARE_PAGES_API_TOKEN }}
      cloudflare-account-id: ${{  secrets.CLOUDFLARE_PAGES_ACCOUNT_ID }}

  publish-vector-basemap-preview:
    name: Publish vector basemap preview
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    concurrency:
      group: basemap-vector-publish-preview
      cancel-in-progress: true
    with:
      style-source-url: https://dev-vector.startupgov.lt/vector
      style-glyphs-url: https://basemap.startupgov.lt/vector/font/{fontstack}/{range}.pbf
      style-sprites-base-url: https://basemap.startupgov.lt/vector/sprite
    secrets:
      cloudflare-api-token: ${{  secrets.CLOUDFLARE_PAGES_API_TOKEN }}
      cloudflare-account-id: ${{  secrets.CLOUDFLARE_PAGES_ACCOUNT_ID }}
