name: "Basemap vector: publish"
run-name: "Basemap vector: publish (${{ startsWith(github.ref, 'refs/tags/') && 'stable' || 'development' }})"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write

jobs:
  publish-vector-basemap:
    name: Publish vector basemap
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: startsWith(github.ref, 'refs/tags/')
    concurrency: basemap-vector-publish
    with:
      docker-image-tag: stable
      archive-version: ${{ github.ref_name }}
      s3-endpoint: ${{ vars.S3_BIIP_ENDPOINT }}
      tile-server-url: https://gis.biip.lt/basemap/grpk
    secrets:
      S3_ACCESS_KEY_ID: ${{ secrets.S3_BIIP_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_BIIP_SECRET_ACCESS_KEY }}

  publish-vector-basemap-preview:
    name: Publish vector basemap preview
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    concurrency:
      group: basemap-vector-publish-preview
      cancel-in-progress: true
    with:
      docker-image-tag: preview
      archive-version: 0.0.0
      s3-endpoint: ${{ vars.S3_DEVELOPMENT_BIIP_ENDPOINT}}
      tile-server-url: https://dev-gis.biip.lt/basemap/grpk
    secrets:
      S3_ACCESS_KEY_ID: ${{ secrets.S3_DEVELOPMENT_BIIP_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_DEVELOPMENT_BIIP_SECRET_ACCESS_KEY }}
