name: "Basemap vector: publish"
run-name: "Basemap vector: publish (${{ startsWith(github.ref, 'refs/tags/') && 'stable' || 'preview' }})"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  publish-vector-basemap:
    name: Publish vector basemap
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: startsWith(github.ref, 'refs/tags/')
    concurrency: basemap-vector-publish
    with:
      docker-image-tag: stable
      archive-version: ${{ github.ref_name }}
      style-source-url: https://gis.biip.lt/basemap/grpk/grpk
      style-glyphs-url: https://basemap.startupgov.lt/vector/font/{fontstack}/{range}.pbf
      style-sprites-base-url: https://basemap.startupgov.lt/vector/sprite

  publish-vector-basemap-preview:
    name: Publish vector basemap preview
    uses: ./.github/workflows/reusable-workflow-publish-basemap-vector.yml
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    concurrency:
      group: basemap-vector-publish-preview
      cancel-in-progress: true
    with:
      docker-image-tag: preview
      archive-version: 0.0.0
      style-source-url: https://gis.biip.lt/basemap/grpk/grpk
      style-glyphs-url: https://basemap.startupgov.lt/vector/font/{fontstack}/{range}.pbf
      style-sprites-base-url: https://basemap.startupgov.lt/vector/sprite
