name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash

  maplibre-style-validate:
    name: Validate MapLibre style specifications
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install maplibre-gl-style-spec
        run: npm install @maplibre/maplibre-gl-style-spec --global

      - name: Validate proton Mapbox GL styles
        working-directory: osm/proton/styles
        run: |
          for file in *.json; do [[ -f "$file" ]] && echo "Validating file: $file" && gl-style-validate "$file"; done

      - name: Validate GRPK Mapbox GL styles
        working-directory: grpk/styles/geoportal
        run: |
          for file in *.json; do [[ -f "$file" ]] && echo "Validating file: $file" && gl-style-validate "$file"; done

  validate-docker-build:
    name: Validate if docker image builds
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/biip-grpk-martin-tile-server
          docker-context: .
          file: grpk/docker/Dockerfile
          environment: stable
          push: false