name: Generate GRPK pmtiles

on:
  pull_request:

permissions: { }

jobs:
  generate-grpk-pmtiles:
    name: Generate GRPK pmtiles
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate GRPK pmtiles
        run: ./gradlew -q run

      - name: Upload GRPK pmtiles
        uses: actions/upload-artifact@v4
        with:
          name: grpk.pmtiles
          path: grpk/data/output/grpk/grpk.pmtiles
          if-no-files-found: error
          compression-level: 0