name: "GRPK: pmtiles generate and deploy"

on:
  push:
    branches: [ main, grpk-deploy ]
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to S3
        type: boolean
        default: false
        required: true

permissions: { }

jobs:
  generate-grpk-pmtiles:
    name: Generate GRPK pmtiles
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate GRPK pmtiles
        run: ./gradlew -q run

      - name: Upload GRPK pmtiles artifact
        uses: actions/upload-artifact@v4
        with:
          name: grpk.pmtiles
          path: grpk/data/output/grpk.pmtiles
          if-no-files-found: error
          compression-level: 0

      - name: Copy style
        if: ${{ inputs.deploy }}
        run: cp -r grpk/styles grpk/data/output

      - name: Sync to S3
        uses: docker://docker.io/rclone/rclone:1.66
        if: ${{ inputs.deploy }}
        with:
          args: "sync grpk/data/output s3:/tiles/grpk --s3-acl=public-read --fast-list --checksum --update --use-server-modtime --metadata --inplace --delete-during"
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_PROVIDER: Other
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.S3_BIIP_ENDPOINT }}
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.S3_BIIP_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_BIIP_SECRET_ACCESS_KEY }}
