name: "POC: static vector basemap"

on:
  pull_request:

jobs:
  generate-vector-basemap:
    name: Generate vector basemap PMTiles
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate vector basemap PMTiles
        uses: ./.github/actions/basemap-vector-generate-pmtiles
        with:
          artifact-retention-days: 1

  generate-vector-mvt-pbfs:
    name: Generate vector basemap MVT pbfs
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container: ghcr.io/osgeo/gdal:ubuntu-full-3.8.5
    needs: generate-vector-basemap
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: vector-basemap-pmtiles
          merge-multiple: true

      - name: Generate mvt pbfs
        run: ogr2ogr -f MVT tiles lithuania.pmtiles -dsco MAXZOOM=14 -oo CLIP=NO
        env:
          GDAL_NUM_THREADS: ALL_CPUS

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tiles

  publish-vector-mvt-pbfs:
    name: Publish vector basemap MVT pbfs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: generate-vector-mvt-pbfs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
