name: "POC: static vector basemap"

on:
  pull_request:

jobs:
  generate-vector-mvt-pbfs:
    name: Generate vector basemap MVT pbfs
    runs-on: ubuntu-latest
    timeout-minutes: 120
    services:
      martin:
        image: ghcr.io/govlt/national-basemap-vector:stable
        ports:
          - 3000:3000
    permissions:
      contents: read
    steps:
      #      - uses: actions/download-artifact@v4
      #        with:
      #          name: vector-basemap-pmtiles
      #          merge-multiple: true

      - run: wget https://cdn.startupgov.lt/tiles/vector/pmtiles/lithuania.pmtiles.layerstats.tsv.gz

      - name: Get all zxy combinations
        run: gunzip -c lithuania.pmtiles.layerstats.tsv.gz | awk -F'\t' '{print $1 "\t" $2 "\t" $3}' | uniq > zxy.tsv

      - name: Generate tiles.json
        run: curl http://localhost:3000/vector --create-dirs -o "tiles/tiles.json" --compressed -s -S

      - name: Change tiles url
        run: jq '.tiles = ["${TILES}"]' tiles.json > tiles.json.tmp && mv tiles.json.tmp tiles.json
        working-directory: tiles
        env:
          TILES: https://vector-static.startupgov.lt/{z}/{x}/{y}.pbf

      - name: Generate MVT pbfs
        run: tail -n +2 zxy.tsv | parallel --colsep '\t' curl "http://localhost:3000/vector/{1}/{2}/{3}" --create-dirs -s -S -o "tiles/{1}/{2}/{3}.pbf" --compressed

      - name: Create tiles archive
        run: zip -r tiles.zip tiles

      - name: Upload to S3
        uses: govlt/national-basemap/.github/actions/rclone-sync@main
        with:
          s3-endpoint: ${{ vars.S3_ENDPOINT }}
          s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          source-path: tiles.zip
          destination-path: /tiles/vector/tiles

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tiles

  publish-basemap-vector-static-docker-image:
    name: Vector static docker image build and push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: generate-vector-mvt-pbfs
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: vector/docker/static/tiles
          merge-multiple: true

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/govlt/national-basemap-vector-static
          docker-context: .
          file: vector/docker/static/Dockerfile
#          environment: ${{ inputs.stable && 'stable' ||  'preview' }}
          environment: preview
          no-cache: true
          push: true
          cache-from: ''
          cache-to: ''


  publish-vector-mvt-pbfs:
    name: Publish vector basemap MVT pbfs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: generate-vector-mvt-pbfs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
