name: "Reusable workflow: publish basemap vector"

on:
  workflow_call:
    inputs:
      s3-endpoint:
        description: Required input to set S3 endpoint
        type: string
        required: true
      archive-version:
        description: Optional input to set PMTiles archive version
        type: string
        default: 0.0.0
      stable:
        description: Optional input to set if publish is stable
        type: boolean
        default: false

    secrets:
      s3-access-key-id:
        description: S3 access key id
        required: true
      s3-secret-access-key:
        description: S3 secret access key
        required: true

jobs:
  generate-basemap-vector-pmtiles:
    name: PMTiles to S3
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change version
        uses: dschanoeh/change-property@v1
        with:
          file: vector/config.properties
          property: archive_version
          value: ${{ inputs.archive-version }}

      - name: Generate PMTiles
        uses: ./.github/actions/basemap-vector-generate-pmtiles
        with:
          cache-data-sources: true

      - name: Upload PMTiles to S3
        uses: ./.github/actions/rclone-sync
        with:
          s3-endpoint: ${{ inputs.s3-endpoint }}
          s3-access-key-id: ${{ secrets.s3-access-key-id }}
          s3-secret-access-key: ${{ secrets.s3-secret-access-key }}
          source-path: vector/data/output
          destination-path: /tiles/vector/pmtiles

  publish-basemap-vector-docker-image:
    name: Docker image build and push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change version
        uses: dschanoeh/change-property@v1
        with:
          file: vector/config.properties
          property: archive_version
          value: ${{ inputs.archive-version }}

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/govlt/national-basemap-vector
          docker-context: .
          file: vector/docker/Dockerfile
          environment: ${{ inputs.stable && 'stable' ||  'preview' }}
          no-cache: true
          push: true
          cache-from: ''
          cache-to: ''
